### ISSUE TITLE
Access control: on- and off-boarding core members

### ISSUE THREAD

**Issue by jaimergp** [jaimergp/auto-issues-example#28]
# 📌 Summary

Document the onboarding and off-boarding process, with the aim of eventually automating most steps.

# 📝 Background

When a user joins any of the conda-forge teams, members of the core team need to manually provision the permissions across the required services.
The list of services and the required permissions are not fully enumerated,
and members sometimes acquire the needed credentials by manually requesting it to other members, as needed.

This also means there's no comprehensive list or way of knowing who has access to each service.

# 🚀 Tasks / Deliverables

- [ ] Document used services and who has access to each one
- [ ] Enumerate who should have access and why, correcting as necessary
- [ ] Automate provisioning as much as possible

# 📅 Estimated completion

...

# ℹ️ References

- ...
- ...
- ...
