### ISSUE TITLE
Quetz maintainers dashboard mockups

### ISSUE THREAD

**Issue by jaimergp** [jaimergp/auto-issues-example#51]
## 📌 Summary

Investigate and design prototype mockups with the desired features for the maintenance board

## 📝 Background

conda-forge.org/status offers a "maintainers dashboard" with information about:

- Operational status of many of the services that conda-forge relies on, including CI, bots, CDN cloning, webservices, documentation...
- Ongoing migrations (collection of PRs automatically issued by the bots)
- Communication about known incidents

This panel has grown organically over the years without significant UX or accessibility analysis. 
We will provide mockups that offer the same functionality with a consistent UI informed by best practices in UX and accessibility.

## 🚀 Tasks / Deliverables

- [ ] Propose a modern conda-forge style guide (taking into account it might be adopted by the main conda-forge.org website too)
- [ ] Survey the community for dashboard panel ideas
- [ ] Provide dashboard mockups following the results of the tasks above

## 📅 Estimated completion

This task should be completed within the first six months.

## ℹ️ References

- [conda-forge.org/status](https://conda-forge.org/status) (implemented in the [`conda-forge/status`](https://github.com/conda-forge/status) repo)
