### ISSUE TITLE
Deploy minimal public Quetz instance

### ISSUE THREAD

**Issue by jaimergp** [jaimergp/auto-issues-example#52]
## 📌 Summary

Deploy a minimal Quetz instance for conda-forge and bioconda

## 📝 Background

[Quetz](https://github.com/mamba-org/quetz) is an open-source server for conda packages and channel metadata.
Its UI frontend can be extended with components.

The idea is to have a running instance that the team can use to iterate on the planned features and receive feedback from the community.

## 🚀 Tasks / Deliverables

- [ ] Decide hosting / domain / infra details
- [ ] Configure vanilla Quetz server and put it online
- [ ] Devise workflow to make the new features available in the preview

## 📅 Estimated completion

This task should be finished within the first six months.

## ℹ️ References

- [Quetz](https://github.com/mamba-org/quetz)
- [beta.mamba.pm](https://beta.mamba.pm/): A running instance of Quetz
- [prefix.dev](https://prefix.dev/): Another server with information about conda channels
